checks:
  php:
    code_rating: true
    check_method_contracts:
      verify_interface_like_constraints: true
      verify_documented_constraints: true
      verify_parent_constraints: true
    duplication: true
    more_specific_types_in_doc_comments: true
    no_goto: true
    no_long_variable_names:
      maximum: '20'
    no_short_method_names:
      minimum: '2'
    no_short_variable_names:
      minimum: '2'
    overriding_parameter: true
    param_doc_comment_if_not_inferrable: true
    parameter_doc_comments: true
    return_doc_comment_if_not_inferrable: true
    return_doc_comments: true
    simplify_boolean_return: true
build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        tests: true
        coverage:
            tests:
                override:
                    -
                        command: vendor/bin/phpunit --coverage-clover clover.xml
                        coverage:
                            file: clover.xml
                            format: clover
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
tools:
  php_analyzer: true
  php_loc: true
  php_mess_detector: true
  php_pdepend: true
  php_sim: true
  sensiolabs_security_checker: true
filter:
  excluded_paths:
    - tests/*