language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

matrix:
    allow_failures:
        - php: '7.2'

before_script:
  - composer install

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: php vendor/bin/phpunit